# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386b9f24d5cc1b902da85300b91905b16c4bd608970d946a7e0335c3ce7fc7c71b675ee4d93482b72a0fd6b2aae377d97838d5bfbfdadb21b815e324cfb79c1b

test:
  secret_key_base: 5ff35ac15cf7ec198c0dad353c7e1feb9d88fabaa99b77b3cec87431475495b03db55f2d675efabd9c439fdb4b7f0693796f544f930efd6b290c1cfc67607c8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
